const express = require('express');
const router = express.Router();
const { getJob } = require('../utils/jobManager');

const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low', 'info'];

function flatFindings(findings = {}) {
  return SEVERITY_ORDER.flatMap((severity) => (
    (findings[severity] || []).map((finding) => ({ ...finding, severity: finding.severity || severity }))
  ));
}

function buildReport(job) {
  const allFindings = flatFindings(job.findings);
  return {
    generated: new Date().toISOString(),
    target: job.target,
    jobId: job.id,
    status: job.status,
    duration: job.completedAt && job.startedAt
      ? Math.round((new Date(job.completedAt) - new Date(job.startedAt)) / 1000)
      : null,
    summary: {
      critical: job.findings.critical.length,
      high: job.findings.high.length,
      medium: job.findings.medium.length,
      low: job.findings.low.length,
      info: job.findings.info.length,
      total: allFindings.length,
    },
    findings: job.findings,
    allFindings,
    reconnaissance: {
      subdomains: job.subdomains || [],
      openPorts: job.openPorts || [],
      liveHosts: job.liveHosts || [],
      tls: job.tls || [],
      endpointCount: (job.endpoints || []).length,
      endpoints: (job.endpoints || []).slice(0, 100),
    },
    errors: job.errors || [],
  };
}

function escapeCell(value) {
  const text = String(value ?? '');
  if (!/[",\n\r]/.test(text)) return text;
  return `"${text.replace(/"/g, '""')}"`;
}

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function toMarkdown(report) {
  const lines = [];
  lines.push('# Omnisect Report');
  lines.push('');
  lines.push(`**Target:** \`${report.target}\``);
  lines.push(`**Generated:** ${report.generated}`);
  lines.push(`**Status:** ${report.status}${report.duration ? ` - ${report.duration}s` : ''}`);
  lines.push(`**Job ID:** \`${report.jobId}\``);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  lines.push('| Severity | Count |');
  lines.push('|---|---|');
  for (const sev of SEVERITY_ORDER) {
    lines.push(`| ${sev.charAt(0).toUpperCase() + sev.slice(1)} | ${report.summary[sev]} |`);
  }
  lines.push(`| **Total** | **${report.summary.total}** |`);
  lines.push('');

  lines.push('## Reconnaissance');
  lines.push('');
  lines.push(`- Subdomains discovered: **${report.reconnaissance.subdomains.length}**`);
  lines.push(`- Open ports: **${report.reconnaissance.openPorts.length}**`);
  lines.push(`- Live hosts: **${report.reconnaissance.liveHosts.length}**`);
  lines.push(`- TLS certificates: **${report.reconnaissance.tls.length}**`);
  lines.push(`- Endpoints crawled: **${report.reconnaissance.endpointCount}**`);
  lines.push('');

  for (const sev of SEVERITY_ORDER) {
    const findings = report.findings[sev] || [];
    if (!findings.length) continue;
    lines.push(`## ${sev.charAt(0).toUpperCase() + sev.slice(1)} (${findings.length})`);
    lines.push('');
    findings.forEach((f, i) => {
      lines.push(`### ${i + 1}. ${f.name || f.description || 'Vulnerability'}${f.isNew ? ' [new]' : ''}`);
      lines.push('');
      if (f.template) lines.push(`- **Template:** \`${f.template}\``);
      lines.push(`- **Type:** ${f.type || 'unknown'}`);
      lines.push(`- **URL:** \`${f.url || ''}\``);
      if (f.payload) lines.push(`- **Payload:** \`${f.payload}\``);
      if (f.triage?.status) lines.push(`- **Triage:** ${f.triage.status}`);
      if (f.triage?.severityOverride) lines.push(`- **Severity override:** ${f.triage.severityOverride}`);
      if (f.triage?.notes) lines.push(`- **Notes:** ${f.triage.notes}`);
      if (f.fingerprint) lines.push(`- **Fingerprint:** \`${f.fingerprint}\``);
      if (f.description && f.name && f.description !== f.name) {
        lines.push('');
        lines.push(f.description);
      }
      if (f.evidence) {
        lines.push('');
        lines.push('**Evidence:**');
        lines.push('```');
        lines.push(String(f.evidence).substring(0, 500));
        lines.push('```');
      }
      if (f.reference) lines.push(`- **Reference:** ${f.reference}`);
      if (f.reproduceCurl || f.url) {
        lines.push('');
        lines.push('**Reproduce:**');
        lines.push('```bash');
        lines.push(f.reproduceCurl || `curl -i "${f.url}"`);
        lines.push('```');
      }
      lines.push('');
    });
  }

  if (report.errors.length) {
    lines.push('## Warnings');
    lines.push('');
    report.errors.forEach((e) => lines.push(`- \`${e}\``));
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by Omnisect - authorized testing only_');
  return lines.join('\n');
}

function toCsv(report) {
  const rows = [[
    'severity', 'type', 'name', 'url', 'payload', 'triage_status', 'severity_override',
    'notes', 'is_new', 'fingerprint', 'reproduce_curl',
  ]];
  for (const finding of report.allFindings) {
    rows.push([
      finding.severity,
      finding.type || '',
      finding.name || finding.description || '',
      finding.url || '',
      finding.payload || '',
      finding.triage?.status || '',
      finding.triage?.severityOverride || '',
      finding.triage?.notes || '',
      finding.isNew ? 'true' : 'false',
      finding.fingerprint || '',
      finding.reproduceCurl || '',
    ]);
  }
  return rows.map((row) => row.map(escapeCell).join(',')).join('\n');
}

function sarifLevel(severity) {
  if (severity === 'critical' || severity === 'high') return 'error';
  if (severity === 'medium') return 'warning';
  return 'note';
}

function toSarif(report) {
  const rules = new Map();
  const results = report.allFindings.map((finding) => {
    const ruleId = `${finding.type || 'finding'}:${finding.template || finding.name || finding.fingerprint || 'generic'}`;
    if (!rules.has(ruleId)) {
      rules.set(ruleId, {
        id: ruleId,
        name: finding.name || finding.type || 'Omnisect finding',
        shortDescription: { text: finding.name || finding.description || 'Omnisect finding' },
        fullDescription: { text: finding.description || finding.name || '' },
        defaultConfiguration: { level: sarifLevel(finding.triage?.severityOverride || finding.severity) },
      });
    }
    return {
      ruleId,
      level: sarifLevel(finding.triage?.severityOverride || finding.severity),
      message: { text: finding.description || finding.name || finding.url || 'Omnisect finding' },
      locations: [{
        physicalLocation: {
          artifactLocation: { uri: finding.url || report.target },
        },
      }],
      properties: {
        severity: finding.severity,
        severityOverride: finding.triage?.severityOverride || null,
        triageStatus: finding.triage?.status || 'new',
        isNew: finding.isNew === true,
        fingerprint: finding.fingerprint || null,
        reproduceCurl: finding.reproduceCurl || null,
      },
    };
  });

  return {
    version: '2.1.0',
    $schema: 'https://json.schemastore.org/sarif-2.1.0.json',
    runs: [{
      tool: {
        driver: {
          name: 'Omnisect',
          informationUri: 'https://localhost',
          rules: [...rules.values()],
        },
      },
      results,
    }],
  };
}

function toHtml(report) {
  const rows = report.allFindings.map((finding) => `
    <tr>
      <td>${escapeHtml(finding.triage?.severityOverride || finding.severity)}</td>
      <td>${escapeHtml(finding.type || '')}</td>
      <td>${escapeHtml(finding.name || finding.description || '')}</td>
      <td><code>${escapeHtml(finding.url || '')}</code></td>
      <td>${escapeHtml(finding.triage?.status || 'new')}</td>
    </tr>`).join('');
  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Omnisect Report - ${escapeHtml(report.target)}</title>
  <style>
    body { margin: 32px; background: #050505; color: #f4f4f4; font: 14px Inter, Arial, sans-serif; }
    h1, h2 { margin: 0 0 12px; }
    .meta { color: #9ca3af; margin-bottom: 24px; }
    table { width: 100%; border-collapse: collapse; margin-top: 18px; }
    th, td { border: 1px solid rgba(255,255,255,.16); padding: 10px; vertical-align: top; }
    th { text-align: left; color: #d1d5db; background: rgba(255,255,255,.06); }
    code { color: #f9fafb; word-break: break-all; }
  </style>
</head>
<body>
  <h1>Omnisect Report</h1>
  <p class="meta">${escapeHtml(report.target)} / ${escapeHtml(report.generated)} / ${escapeHtml(report.status)}</p>
  <h2>Summary</h2>
  <p>Critical: ${report.summary.critical} / High: ${report.summary.high} / Medium: ${report.summary.medium} / Low: ${report.summary.low} / Info: ${report.summary.info}</p>
  <h2>Findings</h2>
  <table>
    <thead><tr><th>Severity</th><th>Type</th><th>Name</th><th>URL</th><th>Triage</th></tr></thead>
    <tbody>${rows || '<tr><td colspan="5">No findings</td></tr>'}</tbody>
  </table>
</body>
</html>`;
}

function attachment(res, job, ext, contentType) {
  res.setHeader('Content-Type', contentType);
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="omnisect-${job.target}-${new Date().toISOString().slice(0, 10)}.${ext}"`,
  );
}

router.get('/:jobId', (req, res) => {
  const job = getJob(req.params.jobId);
  if (!job) return res.status(404).json({ error: 'job not found' });
  const report = buildReport(job);
  const format = String(req.query.format || 'json').toLowerCase();

  if (format === 'md' || format === 'markdown') {
    attachment(res, job, 'md', 'text/markdown; charset=utf-8');
    return res.send(toMarkdown(report));
  }
  if (format === 'csv') {
    attachment(res, job, 'csv', 'text/csv; charset=utf-8');
    return res.send(toCsv(report));
  }
  if (format === 'sarif') {
    attachment(res, job, 'sarif', 'application/sarif+json; charset=utf-8');
    return res.json(toSarif(report));
  }
  if (format === 'html') {
    attachment(res, job, 'html', 'text/html; charset=utf-8');
    return res.send(toHtml(report));
  }

  res.json(report);
});

module.exports = router;
